### PR TITLE
Add redirects for Swift and iOS talks

### PR DESCRIPTION
**Pull request by SkottyK**

### CODE REVIEW

**Comment by jez** [comment]
Thanks @SkottyK! Except, I've been thinking about the redirects for a while, and I don't think they're quite the best solution. For example, half the time when I click the description for my Frontend JavaScript talk, I don't realize that I'm no longer on the CrashCourse site.

Do you want to modify the descriptions to include a link to your external resources, so people definitely know when they're leaving the site?

**Comment by SkottyK** [comment]
Yeah no problem, I'll do that now!

**Comment by SkottyK** [comment]
Wait before I do that, would it be easier if I just added the resources to this CrashCourse site instead of hosting my own? Then they never have to leave the site at all, and formatting will stay consistent.

**Comment by jez** [comment]
Yeah, that'd be great too.

**Comment by jez** [comment]
Oops, didn't realize that this had been updated! Just merged it in from the command line, thanks :D

**Pull request closed without merging**
